### ISSUE TITLE
FEE: attribute url send warning

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_url#21]
attribute url send warning at FE input mask

```
Warning: htmlspecialchars() expects parameter 1 to be string, array given in system/helper/functions.php on line 239
#0 [internal function]: __error(2, 'htmlspecialchar...', '/home/123/w...', 239, Array)
#1 system/helper/functions.php(239): htmlspecialchars(Array, 2, 'utf-8', false)
#2 system/modules/core/templates/forms/form_textfield.html5(20): specialchars(Array)
#3 system/modules/core/library/Contao/BaseTemplate.php(88): include('/home/tsarmac/w...')
#4 system/modules/core/library/Contao/Widget.php(630): Contao\BaseTemplate->parse()
#5 composer/vendor/contao-community-alliance/dc-general-contao-frontend/src/View/WidgetManager.php(150): Contao\Widget->parse()
#6 composer/vendor/contao-community-alliance/dc-general-contao-frontend/src/View/EditMask.php(385): ContaoCommunityAlliance\DcGeneral\ContaoFrontend\View\WidgetManager->renderWidget('youtube', false, NULL)
#7 composer/vendor/contao-community-alliance/dc-general-contao-frontend/src/View/EditMask.php(179): ContaoCommunityAlliance\DcGeneral\ContaoFrontend\View\EditMask->buildFieldSet(Object(ContaoCommunityAlliance\DcGeneral\ContaoFrontend\View\WidgetManager), Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\Palette), NULL)
#8 composer/vendor/contao-community-alliance/dc-general-contao-frontend/src/View/ActionHandler/EditHandler.php(61): ContaoCommunityAlliance\DcGeneral\ContaoFrontend\View\EditMask->execute()
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/View/ActionHandler/AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\ContaoFrontend\View\ActionHandler\EditHandler->process()
#10 system/modules/dc-general-contao-frontend/config/event_listeners.php(52): ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#11 [internal function]: ContaoCommunityAlliance\Contao\EventDispatcher\EventDispatcherInitializer->{closure}(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Object(Closure), Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 composer/vendor/contao-community-alliance/dc-general-contao-frontend/src/FrontendEditor.php(78): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 composer/vendor/metamodels/contao-frontend-editing/src/FrontendEditHybrid.php(64): ContaoCommunityAlliance\DcGeneral\ContaoFrontend\FrontendEditor->editFor('mm_movies', 'create')
#16 system/modules/core/classes/Hybrid.php(239): MetaModels\Contao\FrontendEditing\FrontendEditHybrid->compile()
#17 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(107): Contao\Hybrid->generate()
#18 system/modules/core/library/Contao/Controller.php(484): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#19 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#20 system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
#21 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#22 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#23 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#24 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#25 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#26 index.php(20): Contao\FrontendIndex->run()
#27 {main}
```

**Comment by richardhj** [comment]
metamodels/contao-frontend-editing#10

**Comment by zonky2** [comment]
update MM 2.1

```
Symfony\Component\Debug\Exception\ContextErrorException:
Warning: htmlspecialchars() expects parameter 1 to be string, array given

  at vendor/contao/core-bundle/src/Resources/contao/library/Contao/StringUtil.php:943
  at Contao\StringUtil::specialchars(array('', ''))
     (vendor/contao/core-bundle/src/Resources/contao/templates/forms/form_textfield.html5:20)
  at include('/var/www/virtual/mmodels/test-installation/vendor/contao/core-bundle/src/Resources/contao/templates/forms/form_textfield.html5')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php:96)
  at Contao\Widget->inherit()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php:625)
  at Contao\Widget->parse()
     (vendor/contao-community-alliance/dc-general-contao-frontend/src/View/WidgetManager.php:151)
  at ContaoCommunityAlliance\DcGeneral\ContaoFrontend\View\WidgetManager->renderWidget('private_url', false, null)
     (vendor/contao-community-alliance/dc-general-contao-frontend/src/View/EditMask.php:389)
  at ContaoCommunityAlliance\DcGeneral\ContaoFrontend\View\EditMask->buildFieldSet(object(WidgetManager), object(Palette), null)
     (vendor/contao-community-alliance/dc-general-contao-frontend/src/View/EditMask.php:180)
  at ContaoCommunityAlliance\DcGeneral\ContaoFrontend\View\EditMask->execute()
     (vendor/contao-community-alliance/dc-general-contao-frontend/src/View/ActionHandler/CreateHandler.php:115)
  at ContaoCommunityAlliance\DcGeneral\ContaoFrontend\View\ActionHandler\CreateHandler->process(object(DefaultEnvironment))
     (vendor/contao-community-alliance/dc-general-contao-frontend/src/View/ActionHandler/CreateHandler.php:68)
  at ContaoCommunityAlliance\DcGeneral\ContaoFrontend\View\ActionHandler\CreateHandler->handleEvent(object(ActionEvent), 'dc-general.action', object(TraceableEventDispatcher))
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:111)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(ActionEvent), 'dc-general.action', object(ContainerAwareEventDispatcher))
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:212)
  at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'dc-general.action', object(ActionEvent))
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:44)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.action', object(ActionEvent))
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:143)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('dc-general.action', object(ActionEvent))
     (vendor/contao-community-alliance/dc-general-contao-frontend/src/FrontendEditor.php:86)
  at ContaoCommunityAlliance\DcGeneral\ContaoFrontend\FrontendEditor->editFor('mm_employees', 'create')
     (vendor/metamodels/contao-frontend-editing/src/FrontendEditHybrid.php:92)
  at MetaModels\ContaoFrontendEditingBundle\FrontendEditHybrid->compile()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Hybrid.php:236)
  at Contao\Hybrid->generate()
     (vendor/metamodels/core/src/FrontendIntegration/MetaModelHybrid.php:213)
  at MetaModels\FrontendIntegration\MetaModelHybrid->generate()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:480)
  at Contao\Controller::getContentElement(object(ContentModel), 'main')
     (vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticle.php:183)
  at Contao\ModuleArticle->compile()
     (vendor/contao/core-bundle/src/Resources/contao/modules/Module.php:220)
  at Contao\Module->generate()
     (vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticle.php:65)
  at Contao\ModuleArticle->generate(false)
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:420)
  at Contao\Controller::getArticle(object(ArticleModel), false, false, 'main')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:279)
  at Contao\Controller::getFrontendModule('0', 'main')
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:174)
  at Contao\PageRegular->prepare(object(PageModel))
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:47)
  at Contao\PageRegular->getResponse(object(PageModel), true)
     (vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:306)
  at Contao\FrontendIndex->renderPage(object(Collection))
     (vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:75)
  at Contao\FrontendIndex->run()
     (vendor/contao/core-bundle/src/Controller/FrontendController.php:42)
  at Contao\CoreBundle\Controller\FrontendController->indexAction()
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:64)
```

**Comment by zonky2** [comment]
fixed with next version of https://github.com/contao-community-alliance/contao-textfield-multiple-bundle
